version: '3.9'

services:
  composer:
    image: composer:latest
    command: ['/bin/sh', '-c', "while true; do sleep 1000; done"]
    volumes:
      - ./:/app
      - composer_data:/tmp

volumes:
  composer_data: {}
